#!/usr/bin/env bash

set -eo pipefail   # good practice anyway


CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/job_tools"

mkdir -p "$CONFIG_DIR"


CONFIG_FILE="$CONFIG_DIR/configuration.txt"
DATA_FILE="$CONFIG_DIR/data.txt"
DESTINATION="$HOME/Documents/JOB_APPLICATIONS" 
mkdir -p "$DESTINATION"


source "$CONFIG_FILE"
source "$DATA_FILE"

ROLE_CLEAN=$(echo "$APPLIED_ROLE" | tr '[:lower:]' '[:upper:]' | tr -s ' ' '_')
RESUME_NAME="${NAME_FIRST}_${NAME_LAST}_${ROLE_CLEAN}.md"

FILE=$DESTINATION/$RESUME_NAME

echo "Generating Resume" 

cat > "$FILE" << EOF
# ${NAME_FIRST} ${NAME_LAST} 
<div class="contacts"> 
${CITY}, ${STATE} • ${PHONE} • ${EMAIL} 
</div>

##
${SUMMARY} 


## Professional Experience

**${CURRENT_JOB_POSITION}**
${CURRENT_JOB} - ${CURRENT_JOB_CITY}, ${CURRENT_JOB_STATE}   ${CURRENT_START_YEAR}-${CURRENT_END_YEAR}



- ${CURRENT_JOB_BULLET_ONE}
- ${CURRENT_JOB_BULLET_TWO}
- ${CURRENT_JOB_BULLET_THREE}  



**${SECOND_JOB_POSITION}**
${SECOND_JOB} - ${SECOND_JOB_CITY}, ${SECOND_JOB_STATE}   ${SECOND_START_YEAR}-${SECOND_END_YEAR}



- ${SECOND_JOB_BULLET_ONE}
- ${SECOND_JOB_BULLET_TWO}
- ${SECOND_JOB_BULLET_THREE}

**${THIRD_JOB_POSITION}**
${THIRD_JOB} - ${THIRD_JOB_CITY}, ${THIRD_JOB_STATE}   ${THIRD_START_YEAR}-${THIRD_END_YEAR}


- ${THIRD_JOB_BULLET_ONE}
- ${THIRD_JOB_BULLET_TWO}
- ${THIRD_JOB_BULLET_THREE}


## Education & Relevant Coursework
${HSEDU} - ${HIGHSCHOOL} - ${HSGRADYEAR} 

**Relevent Coursework:** ${HSRELCOURSEWORK}

## Technical Skills & Strengths

- ${SKILLS_TECH}
- ${SKILLS_LOGISTICS}
- ${SKILLS_FABRICATION}
- ${SKILLS_SOFT}

EOF


echo Resume complete!
echo showing ${RESUME_NAME}
cat $FILE
echo -e "\nQuick sanity check:"
echo "Blank lines before <ul> tags:"
grep -c -A 2 '<ul>' "$FILE" | cat -A   # shows $ and blank lines
echo "Ghost-bullet risk: $(tail -20 "$FILE" | grep -c '^$')" blank lines at end
